version: '3.8'

services:
  mysqldb:
    image: mysql:8.0
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${process.env.DB_PASS}
      - MYSQL_DATABASE=${process.env.DB_SCHEMA}
      - MYSQL_USER=${process.env.DB_USER}
      - MYSQL_PASSWORD= ${process.env.DB_PASS}
    ports:
      - 3306:3306
    volumes:
      - ./data/mysql:/var/lib/mysql
  fastfoodservice:
    depends_on:
      - mysqldb
    build: ./
    restart: unless-stopped
    ports:
      - 3000:3000
    environment:
      - DB_HOST=${process.env.DB_HOST}
      - DB_USER=${process.env.DB_USER}
      - DB_PASSWORD= ${process.env.DB_PASS}
      - DB_NAME=${process.env.DB_NAME}
      - DB_PORT=${process.env.DB_PORT}
