apiVersion: v1
kind: Pod
metadata:
  name: fast-food-db
  labels:
    app: fast-food-db
spec:
  containers:
    - name: fast-food-db-container
      image: mysql:8.0
      ports:
      - containerPort: 3306
      env: 
      - name: MYSQL_ROOT_PASSWORD
        value: "@SOAT47fastfood"
      - name: MYSQL_DATABASE
        value: "fastfood-db"
      - name: MYSQL_USER
        value: admin
      - name: MYSQL_PASSWORD
        value: "@SOAT47fastfood"
    
