apiVersion: v1
kind: Pod
metadata:
  name: fast-food-app
  labels:
    app: fast-food-app
spec:
  containers:
   - name: fast-food-app
     image: docker.io/claudioramosti/fastfoodsystem:latest
     ports:
      - containerPort: 3000
     envFrom:
      - configMapRef:
          name: fast-food-app-configmap