name: pipeline
on:
  push:
    branches:
      - pipeline

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Instalar dependências
        run: npm install

      - name: Construir e testar aplicação Node.js
        run: npm test

      - name: Publicar pacote
        run: npm publish

      - name: Limpar o ambiente
        run: npm ci --production

      - name: Notificar sucesso
        run: echo "Aplicação Node.js publicada com sucesso!"
