name: pipeline
on:
  push:
    branches:
      - pipeline

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Instalar dependências
        run: npm install

      - name: Construir e testar aplicação Node.js
        run: npm test

  deploy:
    runs-on: ubuntu-latest
    needs: unit-test

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Instalar dependências
        run: npm install
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, Tag, and Push the Image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: fastfoodsystem
          IMAGE_TAG: latest
        run: |
          aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin 914643601265.dkr.ecr.us-east-1.amazonaws.com
          docker build -t fastfoodsystem . 
          docker tag fastfoodsystem:latest 914643601265.dkr.ecr.us-east-1.amazonaws.com/fastfoodsystem:latest 
          docker push 914643601265.dkr.ecr.us-east-1.amazonaws.com/fastfoodsystem:latest 
