name: pipeline
on:
  push:

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Instalar dependências
        run: npm install

      - name: Construir e testar aplicação Node.js
        run: npm test

  deploy:
    runs-on: ubuntu-latest
    needs: unit-test
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Instalar dependências
        run: npm install
      
      - name: Confiqure AWS Credentials
        uses: aws-actions/configure-aws-credentials@vl
        with:
          aws-access-key-1d: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY })
          aws-region: us-east-1
